# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\"\"\n\nSumRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\"\x15\n\x08SumReply\x12\t\n\x01s\x18\x01 \x01(\x01\"\'\n\x0fMultiplyRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\"\x1f\n\rMultiplyReply\x12\x0e\n\x06result\x18\x01 \x01(\x01\"6\n\x13ReturnBiggerRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\x12\t\n\x01\x63\x18\x03 \x01(\x01\"#\n\x11ReturnBiggerReply\x12\x0e\n\x06result\x18\x01 \x01(\x01\"9\n\x0fQuotientRequest\x12\x11\n\tnumerator\x18\x01 \x01(\x01\x12\x13\n\x0b\x64\x65nominator\x18\x02 \x01(\x01\"/\n\rQuotientReply\x12\x10\n\x08quotient\x18\x01 \x01(\x01\x12\x0c\n\x04rest\x18\x02 \x01(\x01\x32\xc1\x01\n\nCalculator\x12\x1d\n\x03Sum\x12\x0b.SumRequest\x1a\t.SumReply\x12,\n\x08Multiply\x12\x10.MultiplyRequest\x1a\x0e.MultiplyReply\x12\x38\n\x0cReturnBigger\x12\x14.ReturnBiggerRequest\x1a\x12.ReturnBiggerReply\x12,\n\x08Quotient\x12\x10.QuotientRequest\x1a\x0e.QuotientReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUMREQUEST']._serialized_start=20
  _globals['_SUMREQUEST']._serialized_end=54
  _globals['_SUMREPLY']._serialized_start=56
  _globals['_SUMREPLY']._serialized_end=77
  _globals['_MULTIPLYREQUEST']._serialized_start=79
  _globals['_MULTIPLYREQUEST']._serialized_end=118
  _globals['_MULTIPLYREPLY']._serialized_start=120
  _globals['_MULTIPLYREPLY']._serialized_end=151
  _globals['_RETURNBIGGERREQUEST']._serialized_start=153
  _globals['_RETURNBIGGERREQUEST']._serialized_end=207
  _globals['_RETURNBIGGERREPLY']._serialized_start=209
  _globals['_RETURNBIGGERREPLY']._serialized_end=244
  _globals['_QUOTIENTREQUEST']._serialized_start=246
  _globals['_QUOTIENTREQUEST']._serialized_end=303
  _globals['_QUOTIENTREPLY']._serialized_start=305
  _globals['_QUOTIENTREPLY']._serialized_end=352
  _globals['_CALCULATOR']._serialized_start=355
  _globals['_CALCULATOR']._serialized_end=548
# @@protoc_insertion_point(module_scope)
